analyzer:
  errors:
    inference_failure_on_instance_creation: ignore
    inference_failure_on_function_invocation: ignore
    inference_failure_on_function_return_type: ignore
    strict_raw_type: ignore
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: true
